# Server requests

### GET request to example server
GET https://planes-backend-production.up.railway.app/users

### GET request to example server
GET https://planes-backend-production.up.railway.app/users/2

### Send POST request with json body
POST https://planes-backend-production.up.railway.app/users
Content-Type: application/json

{
  "username": "user2",
  "password": "password",
  "email": "email@email",
  "userActive": true
}

### local requests

### GET request to example server
GET http://localhost:8080/users

### GET request to example server
GET http://localhost:8080/users/2

### Send POST request with json body
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "user2",
  "password": "password",
  "email": "email@email",
  "userActive": true
}